# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-11 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='Description',
            field=models.TextField(default=b''),
        ),
    ]
