# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-11 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_auto_20170211_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='Description',
            field=models.TextField(blank=True, default=b'', null=True),
        ),
    ]
