# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-13 11:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_auto_20170211_1255'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'get_latest_by': 'Creation_Data'},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'get_latest_by': 'Creation_Data'},
        ),
    ]
