# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-13 11:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DietType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=64)),
                ('Creation_Data', models.DateTimeField(default=django.utils.timezone.now)),
                ('Description', models.TextField(blank=True, default=b'', null=True)),
                ('Creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=64)),
                ('Creation_Data', models.DateTimeField(default=django.utils.timezone.now)),
                ('Description', models.TextField(blank=True, default=b'', null=True)),
                ('Creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FoodIngredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Number', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=64)),
                ('Creation_Data', models.DateTimeField(default=django.utils.timezone.now)),
                ('Description', models.TextField(blank=True, default=b'', null=True)),
                ('Creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=64)),
                ('Creation_Data', models.DateTimeField(default=django.utils.timezone.now)),
                ('Creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='foodingredient',
            name='Ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diet.Ingredient'),
        ),
        migrations.AddField(
            model_name='foodingredient',
            name='Unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diet.Unit'),
        ),
        migrations.AddField(
            model_name='dish',
            name='Ingredients',
            field=models.ManyToManyField(to='diet.FoodIngredient'),
        ),
        migrations.AddField(
            model_name='dish',
            name='Types',
            field=models.ManyToManyField(to='diet.DietType'),
        ),
    ]
