# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-13 12:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0002_diets'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DietType',
            new_name='IngredientType',
        ),
    ]
