# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-13 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0004_auto_20170213_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='diets',
            name='Description',
            field=models.TextField(blank=True, default=b'', null=True),
        ),
    ]
