# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-13 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0006_foodingredient_creation_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='diets',
            name='Rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='diets',
            name='Rating_Count',
            field=models.IntegerField(default=0),
        ),
    ]
