# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-13 14:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0007_auto_20170213_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='Time',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
    ]
