# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-14 11:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0015_ingredient_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='Types',
            field=models.ManyToManyField(to='diet.IngredientType'),
        ),
    ]
