# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-14 13:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('diet', '0017_ingredientcomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=64)),
                ('Creation_Data', models.DateTimeField(default=django.utils.timezone.now)),
                ('Description', models.TextField(blank=True, default=b'', null=True)),
                ('Creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='meal',
            name='Types',
            field=models.ManyToManyField(to='diet.MealType'),
        ),
    ]
