# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-14 15:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0019_auto_20170214_1621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='Time',
        ),
    ]
