# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-15 10:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('diet', '0023_diet_voters'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='Voters',
            field=models.ManyToManyField(blank=True, related_name='voters_ingre', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='meal',
            name='Voters',
            field=models.ManyToManyField(blank=True, related_name='voters_meal', to=settings.AUTH_USER_MODEL),
        ),
    ]
