# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-15 11:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0024_auto_20170215_1152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='Voters',
        ),
    ]
