# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-15 11:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        ('diet', '0025_remove_ingredient_voters'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('Favorite_Diets', models.ManyToManyField(blank=True, to='diet.Diet')),
                ('Favorive_Meals', models.ManyToManyField(blank=True, to='diet.Meal')),
            ],
        ),
    ]
