# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-15 11:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='Creation_Data',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
