# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-15 11:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_useraccount_creation_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='Favorive_Meals',
            new_name='Favorite_Meals',
        ),
    ]
